### PR TITLE
Practices for accepting contributions

### PR DESCRIPTION
**Pull request by pkalliok**
Some common practices for accepting contributions

### CODE REVIEW

**Review by igordavydsson — APPROVED** [review]
looks pretty good! nice :clap:

**Review by a-rmz — APPROVED** [review]
LGTM

**Comment by Nizar-Rahme** [comment]
Looks good!
Also adding a [CONTRIBUTING.md](https://mozillascience.github.io/working-open-workshop/contributing/) file and GitHub templates for opening issues would come in handy

**Comment by pkalliok** [comment]
Good point Nizar.  Maybe I'll include these in documentation req's in wiki?

**Review by tituomin — APPROVED** [review]

**Pull request merged**
